CREATE TABLE audit_records (
    id CHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(191) NOT NULL,
    actor_id VARCHAR(191) NOT NULL,
    actor_type VARCHAR(64) NOT NULL,
    action VARCHAR(191) NOT NULL,
    resource_type VARCHAR(191) NOT NULL,
    resource_id VARCHAR(191) NOT NULL,
    request_id VARCHAR(191) NOT NULL DEFAULT '',
    trace_id VARCHAR(191) NOT NULL DEFAULT '',
    source_service VARCHAR(191) NOT NULL,
    before_summary JSON NULL,
    after_summary JSON NULL,
    occurred_at DATETIME(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by TEXT NOT NULL,
    updated_by TEXT NOT NULL,
    INDEX audit_records_tenant_time_idx (tenant_id, occurred_at DESC, id),
    INDEX audit_records_resource_idx (tenant_id, resource_type, resource_id, occurred_at DESC),
    INDEX audit_records_actor_idx (tenant_id, actor_id, occurred_at DESC),
    INDEX audit_records_request_idx (request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
